In [17]:
# load the UNSW_NB15 training dataset
import pandas as pd
import numpy as np

#df = pd.read_csv('https://www.unsw.adfa.edu.au/australian-centre-for-cyber-security/cybersecurity/ADFA-NB15-Datasets/a%20part%20of%20training%20and%20testing%20set/UNSW_NB15_training-set.csv') # read in the csv file
df = pd.read_csv('C:/Users/sg0207348/Documents/smu/UNSW_NB15_training_set.csv') # read in the csv file

df.head()

,﻿id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.000011,udp,-,INT,2,0,496,0,90909.0902,...,1,2,0,0,0,1,2,0,Normal,0
1,2,0.000008,udp,-,INT,2,0,1762,0,125000.0003,...,1,2,0,0,0,1,2,0,Normal,0
2,3,0.000005,udp,-,INT,2,0,1068,0,200000.0051,...,1,3,0,0,0,1,3,0,Normal,0
3,4,0.000006,udp,-,INT,2,0,900,0,166666.6608,...,1,3,0,0,0,2,3,0,Normal,0
4,5,0.000010,udp,-,INT,2,0,2126,0,100000.0025,...,1,3,0,0,0,2,3,0,Normal,0

In [4]:
df.describe()

,﻿id,dur,spkts,dpkts,sbytes,dbytes,rate,sttl,dttl,sload,...,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,label
count,82332.000000,82332.000000,82332.000000,82332.000000,8.233200e+04,8.233200e+04,8.233200e+04,82332.000000,82332.000000,8.233200e+04,...,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000
mean,41166.500000,1.006756,18.666472,17.545936,7.993908e+03,1.323379e+04,8.241089e+04,180.967667,95.713003,6.454902e+07,...,4.928898,3.663011,7.456360,0.008284,0.008381,0.129743,6.468360,9.164262,0.011126,0.550600
std,23767.345519,4.710444,133.916353,115.574086,1.716423e+05,1.514715e+05,1.486204e+05,101.513358,116.667722,1.798618e+08,...,8.389545,5.915386,11.415191,0.091171,0.092485,0.638683,8.543927,11.121413,0.104891,0.497436
min,1.000000,0.000000,1.000000,0.000000,2.400000e+01,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,20583.750000,0.000008,2.000000,0.000000,1.140000e+02,0.000000e+00,2.860611e+01,62.000000,0.000000,1.120247e+04,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000
50%,41166.500000,0.014138,6.000000,2.000000,5.340000e+02,1.780000e+02,2.650177e+03,254.000000,29.000000,5.770032e+05,...,1.000000,1.000000,3.000000,0.000000,0.000000,0.000000,3.000000,5.000000,0.000000,1.000000
75%,61749.250000,0.719360,12.000000,10.000000,1.280000e+03,9.560000e+02,1.111111e+05,254.000000,252.000000,6.514286e+07,...,4.000000,3.000000,6.000000,0.000000,0.000000,0.000000,7.000000,11.000000,0.000000,1.000000
max,82332.000000,59.999989,10646.000000,11018.000000,1.435577e+07,1.465753e+07,1.000000e+06,255.000000,253.000000,5.268000e+09,...,59.000000,38.000000,63.000000,2.000000,2.000000,16.000000,60.000000,62.000000,1.000000,1.000000

In [21]:
print (df.dtypes)
print (df.info)

﻿id                    int64
dur                  float64
proto                 object
service               object
state                 object
spkts                  int64
dpkts                  int64
sbytes                 int64
dbytes                 int64
rate                 float64
sttl                   int64
dttl                   int64
sload                float64
dload                float64
sloss                  int64
dloss                  int64
sinpkt               float64
dinpkt               float64
sjit                 float64
djit                 float64
swin                   int64
stcpb                  int64
dtcpb                  int64
dwin                   int64
tcprtt               float64
synack               float64
ackdat               float64
smean                  int64
dmean                  int64
trans_depth            int64
response_body_len      int64
ct_srv_src             int64
ct_state_ttl           int64
ct_dst_ltm             int64
ct_src_dport_ltm       int64
ct_dst_sport_ltm       int64
ct_dst_src_ltm         int64
is_ftp_login           int64
ct_ftp_cmd             int64
ct_flw_http_mthd       int64
ct_src_ltm             int64
ct_srv_dst             int64
is_sm_ips_ports        int64
attack_cat            object
label                  int64
dtype: object
<bound method DataFrame.info of          ﻿id       dur proto service state  spkts  dpkts  sbytes  dbytes  \
0          1  0.000011   udp       -   INT      2      0     496       0
1          2  0.000008   udp       -   INT      2      0    1762       0
2          3  0.000005   udp       -   INT      2      0    1068       0
3          4  0.000006   udp       -   INT      2      0     900       0
4          5  0.000010   udp       -   INT      2      0    2126       0
5          6  0.000003   udp       -   INT      2      0     784       0
6          7  0.000006   udp       -   INT      2      0    1960       0
7          8  0.000028   udp       -   INT      2      0    1384       0
8          9  0.000000   arp       -   INT      1      0      46       0
9         10  0.000000   arp       -   INT      1      0      46       0
10        11  0.000000   arp       -   INT      1      0      46       0
11        12  0.000000   arp       -   INT      1      0      46       0
12        13  0.000004   udp       -   INT      2      0    1454       0
13        14  0.000007   udp       -   INT      2      0    2062       0
14        15  0.000011   udp       -   INT      2      0    2040       0
15        16  0.000004   udp       -   INT      2      0    1052       0
16        17  0.000003   udp       -   INT      2      0     314       0
17        18  0.000010   udp       -   INT      2      0    1774       0
18        19  0.000002   udp       -   INT      2      0    1568       0
19        20  0.000004   udp       -   INT      2      0    2054       0
20        21  0.000010   udp       -   INT      2      0    2170       0
21        22  0.000009   udp       -   INT      2      0     202       0
22        23  0.000010   udp       -   INT      2      0    1334       0
23        24  0.000005   udp       -   INT      2      0    2058       0
24        25  0.000003   udp       -   INT      2      0     286       0
25        26  0.000007   udp       -   INT      2      0    1500       0
26        27  0.000006   udp       -   INT      2      0     902       0
27        28  0.000002   udp       -   INT      2      0    1626       0
28        29  0.000007   udp       -   INT      2      0     364       0
29        30  1.434166   tcp       -   FIN     10      6     530     268
...      ...       ...   ...     ...   ...    ...    ...     ...     ...
82302  82303  0.449797   tcp       -   FIN     10      6     588     268
82303  82304  0.870010   tcp       -   FIN     10      6     588     268
82304  82305  1.766424   tcp       -   FIN     10      8     588     354
82305  82306  1.025080   tcp       -   FIN     10      6     588     268
82306  82307  0.498365   tcp       -   FIN     10      6     588     268
82307  82308  0.971427   tcp       -   FIN     10      8     588     354
82308  82309  0.467263   tcp       -   FIN     10      6     588     268
82309  82310  1.026355   tcp       -   FIN     10      8     588     354
82310  82311  1.363057   tcp       -   FIN     10      8     588     354
82311  82312  0.888738   tcp       -   FIN     10      6     588     268
82312  82313  1.173606   tcp       -   FIN     10      8     588     354
82313  82314  0.000009   udp       -   INT      2      0     104       0
82314  82315  0.524434   tcp       -   FIN     10      6     588     268
82315  82316  0.000001   udp       -   INT      2      0     104       0
82316  82317  0.000001   udp       -   INT      2      0     104       0
82317  82318  0.947039   tcp       -   FIN     10      6     588     268
82318  82319  0.000009   udp       -   INT      2      0     104       0
82319  82320  0.811914   tcp       -   FIN     10      6     588     268
82320  82321  0.000010   udp       -   INT      2      0     104       0
82321  82322  0.000001   udp       -   INT      2      0     104       0
82322  82323  0.000004   udp       -   INT      2      0     104       0
82323  82324  5.167410   tcp       -   FIN    108     24  138067    1042
82324  82325  0.000006   udp       -   INT      2      0     104       0
82325  82326  0.000010   udp       -   INT      2      0     104       0
82326  82327  0.000009   udp       -   INT      2      0     104       0
82327  82328  0.000005   udp       -   INT      2      0     104       0
82328  82329  1.106101   tcp       -   FIN     20      8   18062     354
82329  82330  0.000000   arp       -   INT      1      0      46       0
82330  82331  0.000000   arp       -   INT      1      0      46       0
82331  82332  0.000009   udp       -   INT      2      0     104       0

               rate  ...    ct_dst_sport_ltm  ct_dst_src_ltm  is_ftp_login  \
0      9.090909e+04  ...                   1               2             0
1      1.250000e+05  ...                   1               2             0
2      2.000000e+05  ...                   1               3             0
3      1.666667e+05  ...                   1               3             0
4      1.000000e+05  ...                   1               3             0
5      3.333333e+05  ...                   1               2             0
6      1.666667e+05  ...                   1               2             0
7      3.571429e+04  ...                   1               3             0
8      0.000000e+00  ...                   2               2             0
9      0.000000e+00  ...                   2               2             0
10     0.000000e+00  ...                   2               2             0
11     0.000000e+00  ...                   2               2             0
12     2.500000e+05  ...                   1               3             0
13     1.428571e+05  ...                   1               3             0
14     9.090909e+04  ...                   1               1             0
15     2.500000e+05  ...                   1               3             0
16     3.333333e+05  ...                   1               2             0
17     1.000000e+05  ...                   1               2             0
18     5.000000e+05  ...                   1               2             0
19     2.500000e+05  ...                   1               2             0
20     1.000000e+05  ...                   1               2             0
21     1.111111e+05  ...                   1               2             0
22     1.000000e+05  ...                   1               3             0
23     2.000000e+05  ...                   1               3             0
24     3.333333e+05  ...                   1               3             0
25     1.428571e+05  ...                   1               2             0
26     1.666667e+05  ...                   1               2             0
27     5.000000e+05  ...                   1               1             0
28     1.428571e+05  ...                   1               1             0
29     1.045904e+01  ...                   1               1             0
...             ...  ...                 ...             ...           ...
82302  3.334838e+01  ...                   1               2             0
82303  1.724118e+01  ...                   1               2             0
82304  9.623964e+00  ...                   1               1             0
82305  1.463300e+01  ...                   1               1             0
82306  3.009842e+01  ...                   1               1             0
82307  1.750003e+01  ...                   1               2             0
82308  3.210183e+01  ...                   1               2             0
82309  1.656347e+01  ...                   1               2             0
82310  1.247196e+01  ...                   1               2             0
82311  1.687786e+01  ...                   1               2             0
82312  1.448527e+01  ...                   1               1             0
82313  1.111111e+05  ...                   1               1             0
82314  2.860227e+01  ...                   1               1             0
82315  1.000000e+06  ...                   1               2             0
82316  1.000000e+06  ...                   1               2             0
82317  1.583884e+01  ...                   1               4             0
82318  1.111111e+05  ...                   1               2             0
82319  1.847486e+01  ...                   1               4             0
82320  1.000000e+05  ...                   1               2             0
82321  1.000000e+06  ...                   1               2             0
82322  2.500000e+05  ...                   1               1             0
82323  2.535119e+01  ...                   1               1             0
82324  1.666667e+05  ...                   1               2             0
82325  1.000000e+05  ...                   1               2             0
82326  1.111111e+05  ...                   1               1             0
82327  2.000000e+05  ...                   1               2             0
82328  2.441007e+01  ...                   1               1             0
82329  0.000000e+00  ...                   1               1             0
82330  0.000000e+00  ...                   1               1             0
82331  1.111111e+05  ...                   1               1             0

       ct_ftp_cmd  ct_flw_http_mthd  ct_src_ltm  ct_srv_dst  is_sm_ips_ports  \
0               0                 0           1           2                0
1               0                 0           1           2                0
2               0                 0           1           3                0
3               0                 0           2           3                0
4               0                 0           2           3                0
5               0                 0           2           2                0
6               0                 0           2           2                0
7               0                 0           1           3                0
8               0                 0           2           2                1
9               0                 0           2           2                1
10              0                 0           2           2                1
11              0                 0           2           2                1
12              0                 0           1           3                0
13              0                 0           1           3                0
14              0                 0           1           1                0
15              0                 0           2           3                0
16              0                 0           1           2                0
17              0                 0           1           2                0
18              0                 0           1           2                0
19              0                 0           2           2                0
20              0                 0           1           2                0
21              0                 0           1           2                0
22              0                 0           1           3                0
23              0                 0           2           3                0
24              0                 0           2           3                0
25              0                 0           2           2                0
26              0                 0           2           2                0
27              0                 0           2           1                0
28              0                 0           2           2                0
29              0                 0           1           1                0
...           ...               ...         ...         ...              ...
82302           0                 0           1           2                0
82303           0                 0           1           2                0
82304           0                 0           1           1                0
82305           0                 0           1           1                0
82306           0                 0           1           1                0
82307           0                 0           2           2                0
82308           0                 0           2           2                0
82309           0                 0           1           2                0
82310           0                 0           1           2                0
82311           0                 0           1           2                0
82312           0                 0           1           1                0
82313           0                 0           1           1                0
82314           0                 0           1           1                0
82315           0                 0           1           2                0
82316           0                 0           2           2                0
82317           0                 0           1           4                0
82318           0                 0           1           2                0
82319           0                 0           1           4                0
82320           0                 0           1           2                0
82321           0                 0           1           2                0
82322           0                 0           1           1                0
82323           0                 0           1           3                0
82324           0                 0           1           2                0
82325           0                 0           1           2                0
82326           0                 0           1           1                0
82327           0                 0           2           1                0
82328           0                 0           3           2                0
82329           0                 0           1           1                1
82330           0                 0           1           1                1
82331           0                 0           1           1                0

       attack_cat  label
0          Normal      0
1          Normal      0
2          Normal      0
3          Normal      0
4          Normal      0
5          Normal      0
6          Normal      0
7          Normal      0
8          Normal      0
9          Normal      0
10         Normal      0
11         Normal      0
12         Normal      0
13         Normal      0
14         Normal      0
15         Normal      0
16         Normal      0
17         Normal      0
18         Normal      0
19         Normal      0
20         Normal      0
21         Normal      0
22         Normal      0
23         Normal      0
24         Normal      0
25         Normal      0
26         Normal      0
27         Normal      0
28         Normal      0
29         Normal      0
...           ...    ...
82302      Normal      0
82303      Normal      0
82304      Normal      0
82305      Normal      0
82306      Normal      0
82307      Normal      0
82308      Normal      0
82309      Normal      0
82310      Normal      0
82311      Normal      0
82312      Normal      0
82313      Normal      0
82314      Normal      0
82315      Normal      0
82316      Normal      0
82317      Normal      0
82318      Normal      0
82319      Normal      0
82320      Normal      0
82321      Normal      0
82322      Normal      0
82323      Normal      0
82324      Normal      0
82325      Normal      0
82326      Normal      0
82327      Normal      0
82328      Normal      0
82329      Normal      0
82330      Normal      0
82331      Normal      0

[82332 rows x 45 columns]>

In [22]:
normalPacketPercent = float(len(df[df.label==0]))/len(df)*100.0
attackPacketPercent = float(len(df[df.label==1]))/len(df)*100.0

print ('normal packet percentage: ',  normalPacketPercent)
print ('attack packet percentage: ',  attackPacketPercent)

normal packet percentage:  44.939999028324344
attack packet percentage:  55.06000097167566